### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by Steven-G-Jet** [upxlabs/magic-buttons-sketch-plugin#3]
Great plugin, thank you for making this! You might want to consider adding these points to your instruction:
1. You made the padding symbol fixed width-which is a very important step, but you didn't mention it in your instruction
2. It seems like the name "padding" is case-sensitive. When I used "Padding-left", the plugin couldn't read it.

**Comment by calderaricaio** [comment]
Hi Steven! Thanks for your considerations. The case sensitive detail is being said in the instructions (lowercase only) right after the info about padding left and right where I talk about the button structure inside Readme. I will add the info about the fixed width but with the example files pretty much everything is covered when you look at the examples.
